// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function BuildGrowthUTM(arg1) {
  return window['go']['main']['App']['BuildGrowthUTM'](arg1);
}

export function BuildPrompt(arg1) {
  return window['go']['main']['App']['BuildPrompt'](arg1);
}

export function CancelFacebookGeneration(arg1) {
  return window['go']['main']['App']['CancelFacebookGeneration'](arg1);
}

export function CancelGrowthGeneration(arg1) {
  return window['go']['main']['App']['CancelGrowthGeneration'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeleteGrowthExperiment(arg1) {
  return window['go']['main']['App']['DeleteGrowthExperiment'](arg1);
}

export function DeleteGrowthLead(arg1) {
  return window['go']['main']['App']['DeleteGrowthLead'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function EvaluateContent(arg1, arg2) {
  return window['go']['main']['App']['EvaluateContent'](arg1, arg2);
}

export function ExportProject(arg1, arg2) {
  return window['go']['main']['App']['ExportProject'](arg1, arg2);
}

export function FacebookBootstrap() {
  return window['go']['main']['App']['FacebookBootstrap']();
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GenerateFacebookPack(arg1) {
  return window['go']['main']['App']['GenerateFacebookPack'](arg1);
}

export function GenerateGrowthPack(arg1) {
  return window['go']['main']['App']['GenerateGrowthPack'](arg1);
}

export function GetLatestFacebookPack() {
  return window['go']['main']['App']['GetLatestFacebookPack']();
}

export function GetLatestGrowthPack() {
  return window['go']['main']['App']['GetLatestGrowthPack']();
}

export function GrowthBootstrap() {
  return window['go']['main']['App']['GrowthBootstrap']();
}

export function LaunchDownloadedUpdate(arg1) {
  return window['go']['main']['App']['LaunchDownloadedUpdate'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function ReviewGrowthPack(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReviewGrowthPack'](arg1, arg2, arg3);
}

export function SaveGrowthExperiment(arg1) {
  return window['go']['main']['App']['SaveGrowthExperiment'](arg1);
}

export function SaveGrowthLead(arg1) {
  return window['go']['main']['App']['SaveGrowthLead'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SyncFacebookBrief(arg1) {
  return window['go']['main']['App']['SyncFacebookBrief'](arg1);
}

export function SyncGrowthBrief(arg1) {
  return window['go']['main']['App']['SyncGrowthBrief'](arg1);
}
