// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {measurement} from '../models';
import {updater} from '../models';
import {main} from '../models';
import {facebookcompanion} from '../models';
import {workbench} from '../models';
import {salesops} from '../models';

export function Bootstrap():Promise<domain.BootstrapData>;

export function BuildGrowthUTM(arg1:measurement.UTMRequest):Promise<measurement.UTMResult>;

export function BuildPrompt(arg1:domain.ContentBrief):Promise<domain.PromptPreview>;

export function CancelFacebookGeneration(arg1:string):Promise<boolean>;

export function CancelGrowthGeneration(arg1:string):Promise<boolean>;

export function CheckForUpdates():Promise<updater.Info>;

export function DeleteGrowthExperiment(arg1:string):Promise<void>;

export function DeleteGrowthLead(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<updater.Info>;

export function EvaluateContent(arg1:domain.ContentBrief,arg2:domain.GeneratedContent):Promise<domain.QualityReport>;

export function ExportProject(arg1:domain.Project,arg2:string):Promise<string>;

export function FacebookBootstrap():Promise<main.FacebookBootstrapData>;

export function GenerateContent(arg1:domain.GenerationRequest):Promise<domain.GenerationResult>;

export function GenerateFacebookPack(arg1:main.FacebookGenerationRequest):Promise<facebookcompanion.PackSnapshot>;

export function GenerateGrowthPack(arg1:main.GrowthGenerationRequest):Promise<workbench.PackSnapshot>;

export function GetLatestFacebookPack():Promise<main.FacebookLatestResult>;

export function GetLatestGrowthPack():Promise<main.GrowthLatestResult>;

export function GrowthBootstrap():Promise<main.GrowthBootstrapData>;

export function LaunchDownloadedUpdate(arg1:string):Promise<void>;

export function ListProjects():Promise<Array<domain.ProjectSummary>>;

export function LoadProject(arg1:string):Promise<domain.Project>;

export function ReviewGrowthPack(arg1:string,arg2:string,arg3:string):Promise<workbench.PackSnapshot>;

export function SaveGrowthExperiment(arg1:measurement.Experiment):Promise<measurement.ExperimentView>;

export function SaveGrowthLead(arg1:salesops.Lead):Promise<salesops.Lead>;

export function SaveProject(arg1:domain.Project):Promise<domain.Project>;

export function SaveSettings(arg1:domain.ProviderSettings):Promise<void>;

export function SyncFacebookBrief(arg1:facebookcompanion.Brief):Promise<main.FacebookBriefReceipt>;

export function SyncGrowthBrief(arg1:workbench.GrowthBrief):Promise<main.GrowthBriefReceipt>;
